name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Zig
        uses: mlugg/setup-zig@v1 # TODO: Pin SHA
        with:
          version: 0.15.0

      - name: Build
        run: zig build

      - name: Run Unit Tests
        run: zig build test

      - name: Run Golden Tests
        run: zig build test-golden

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: mlugg/setup-zig@v1 # TODO: Pin SHA
        with:
          version: 0.15.0
      - run: zig fmt --check src/
